branches:
  only:
    - master
    - dev

language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests!"

script:
  # Build & Tag
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed eyobs/udagram-api-feed:v1
  - docker build -t udagram-api-user ./udagram-api-user
  - docker tag udagram-api-user eyobs/udagram-api-user:v1
  - docker build -t udagram-frontend ./udagram-frontend
  - docker tag udagram-frontend eyobs/udagram-frontend:v1
  - docker build -t udagram-reverseproxy ./udagram-reverseproxy
  - docker tag udagram-reverseproxy eyobs/udagram-reverseproxy:v1

after_success:
  # Push
  # Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push  eyobs/udagram-reverse-proxy:v1
  - docker push  eyobs/udagram-frontend:v1
  - docker push  eyobs/udagram-users-microservice:v1
  - docker push  eyobs/udagram-feed-microservice:v1